[package]
name = "igloo-shell-tui"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Christopher Scott"]

[[bin]]
name = "igloo-shell-tui"
path = "src/main.rs"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
igloo-shell-core = { path = "../igloo-shell-core" }
